<a href="https://colab.research.google.com/github/Riti13/global_cost_of_living_ML/blob/main/cost_of_living_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#REGRESSION

1. MULTIPLE REGRESSION



In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data=pd.read_csv('/content/cost-of-living.csv')
data

Unnamed: 0                city      country     x1     x2     x3     x4  \
0              0               Delhi        India   4.90  22.04   4.28   1.84   
1              1            Shanghai        China   5.59  40.51   5.59   1.12   
2              2             Jakarta    Indonesia   2.54  22.25   3.50   2.02   
3              3              Manila  Philippines   3.54  27.40   3.54   1.24   
4              4               Seoul  South Korea   7.16  52.77   6.03   3.02   
...          ...                 ...          ...    ...    ...    ...    ...   
4869        4869        Peterborough    Australia    NaN    NaN    NaN    NaN   
4870        4870          Georgetown    Australia    NaN    NaN    NaN    NaN   
4871        4871  Ixtapa Zihuatanejo       Mexico   5.19  31.13  12.97   0.99   
4872        4872             Iqaluit       Canada  29.78  74.61  13.77   6.70   
4873        4873              Neiafu        Tonga    NaN  29.53  10.55  10.55   

        x5    x6    x7  ...     x47      x48     x49      x50      x51  \
0     3.67  1.78  0.48  ...   36.26   223.87  133.38   596.16   325.82   
1     4.19  3.96  0.52  ...  121.19  1080.07  564.30  2972.57  1532.23   
2     3.18  2.19  0.59  ...   80.32   482.85  270.15  1117.69   584.37   
3     1.90  2.91  0.93  ...   61.82   559.52  281.78  1754.40   684.81   
4     4.52  3.86  1.46  ...  108.30   809.83  583.60  2621.05  1683.74   
...    ...   ...   ...  ...     ...      ...     ...      ...      ...   
4869   NaN   NaN   NaN  ...     NaN      NaN     NaN      NaN      NaN   
4870   NaN   NaN   NaN  ...     NaN      NaN     NaN      NaN      NaN   
4871   NaN  1.82  0.62  ...  103.78   415.11  259.44   518.89   415.11   
4872  8.93  3.72  3.54  ...     NaN      NaN     NaN  2978.11  2978.11   
4873   NaN   NaN  2.11  ...     NaN      NaN     NaN      NaN      NaN   

           x52       x53      x54   x55  data_quality  
0      2619.46   1068.90   586.35  7.96             1  
1     17333.09   9174.88  1382.83  5.01             1  
2      2694.05   1269.44   483.19  9.15             1  
3      3536.04   2596.44   419.02  7.80             1  
4     21847.94  10832.90  2672.23  3.47             1  
...        ...       ...      ...   ...           ...  
4869       NaN       NaN      NaN   NaN             0  
4870       NaN       NaN      NaN   NaN             0  
4871       NaN       NaN      NaN   NaN             0  
4872       NaN       NaN      NaN  6.53             0  
4873       NaN       NaN      NaN   NaN             0  

[4874 rows x 59 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4874 entries, 0 to 4873
Data columns (total 59 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Unnamed: 0    4874 non-null   int64  
 1   city          4874 non-null   object 
 2   country       4874 non-null   object 
 3   x1            4449 non-null   float64
 4   x2            4432 non-null   float64
 5   x3            4552 non-null   float64
 6   x4            4385 non-null   float64
 7   x5            4445 non-null   float64
 8   x6            4540 non-null   float64
 9   x7            4438 non-null   float64
 10  x8            4571 non-null   float64
 11  x9            4494 non-null   float64
 12  x10           4457 non-null   float64
 13  x11           4538 non-null   float64
 14  x12           4369 non-null   float64
 15  x13           4393 non-null   float64
 16  x14           4318 non-null   float64
 17  x15           4312 non-null   float64
 18  x16           4509 non-null 

In [ ]:
data=data.fillna(value=0)

In [ ]:
X=data.iloc[:,3:-1].values
y=data.iloc[:,-1].values


In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=0.2)


In [ ]:
from sklearn.linear_model import LinearRegression
mreg=LinearRegression()
mreg.fit(xtrain,ytrain)
pred=mreg.predict(xtest)

In [ ]:
from sklearn.metrics import mean_squared_error
r=np.sqrt(mean_squared_error(ytest,pred))
r

0.34360146796301394

2.polynomial regression

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data=pd.read_csv('/content/cost-of-living.csv')
data=data.fillna(value=0)

In [ ]:
X=data.iloc[:,3:-1].values
y=data.iloc[:,-1].values

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
obj=PolynomialFeatures(degree=3)

In [ ]:
x_poly=obj.fit_transform(X)
x_poly

array([[1.00000000e+00, 4.90000000e+00, 2.20400000e+01, ...,
        2.73669833e+06, 3.71520742e+04, 5.04358336e+02],
       [1.00000000e+00, 5.59000000e+00, 4.05100000e+01, ...,
        9.58021623e+06, 3.47091713e+04, 1.25751501e+02],
       [1.00000000e+00, 2.54000000e+00, 2.22500000e+01, ...,
        2.13627407e+06, 4.04538748e+04, 7.66060875e+02],
       ...,
       [1.00000000e+00, 5.19000000e+00, 3.11300000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 2.97800000e+01, 7.46100000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 2.78445077e+02],
       [1.00000000e+00, 0.00000000e+00, 2.95300000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [ ]:
from sklearn.linear_model import LinearRegression
preg=LinearRegression()
preg.fit(x_poly,y)

LinearRegression()

In [ ]:
pred=preg.predict(x_poly)

In [ ]:
from sklearn.metrics import mean_squared_error,r2_score

In [ ]:
r=np.sqrt(mean_squared_error(y,pred))
score=r2_score(y,pred)
r

0.0001580787028555138

In [ ]:
score

0.9999998354330051

3.decision tree

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data=pd.read_csv('/content/cost-of-living.csv')
data=data.fillna(value=0)
data

Unnamed: 0                city      country     x1     x2     x3     x4  \
0              0               Delhi        India   4.90  22.04   4.28   1.84   
1              1            Shanghai        China   5.59  40.51   5.59   1.12   
2              2             Jakarta    Indonesia   2.54  22.25   3.50   2.02   
3              3              Manila  Philippines   3.54  27.40   3.54   1.24   
4              4               Seoul  South Korea   7.16  52.77   6.03   3.02   
...          ...                 ...          ...    ...    ...    ...    ...   
4869        4869        Peterborough    Australia   0.00   0.00   0.00   0.00   
4870        4870          Georgetown    Australia   0.00   0.00   0.00   0.00   
4871        4871  Ixtapa Zihuatanejo       Mexico   5.19  31.13  12.97   0.99   
4872        4872             Iqaluit       Canada  29.78  74.61  13.77   6.70   
4873        4873              Neiafu        Tonga   0.00  29.53  10.55  10.55   

        x5    x6    x7  ...     x47      x48     x49      x50      x51  \
0     3.67  1.78  0.48  ...   36.26   223.87  133.38   596.16   325.82   
1     4.19  3.96  0.52  ...  121.19  1080.07  564.30  2972.57  1532.23   
2     3.18  2.19  0.59  ...   80.32   482.85  270.15  1117.69   584.37   
3     1.90  2.91  0.93  ...   61.82   559.52  281.78  1754.40   684.81   
4     4.52  3.86  1.46  ...  108.30   809.83  583.60  2621.05  1683.74   
...    ...   ...   ...  ...     ...      ...     ...      ...      ...   
4869  0.00  0.00  0.00  ...    0.00     0.00    0.00     0.00     0.00   
4870  0.00  0.00  0.00  ...    0.00     0.00    0.00     0.00     0.00   
4871  0.00  1.82  0.62  ...  103.78   415.11  259.44   518.89   415.11   
4872  8.93  3.72  3.54  ...    0.00     0.00    0.00  2978.11  2978.11   
4873  0.00  0.00  2.11  ...    0.00     0.00    0.00     0.00     0.00   

           x52       x53      x54   x55  data_quality  
0      2619.46   1068.90   586.35  7.96             1  
1     17333.09   9174.88  1382.83  5.01             1  
2      2694.05   1269.44   483.19  9.15             1  
3      3536.04   2596.44   419.02  7.80             1  
4     21847.94  10832.90  2672.23  3.47             1  
...        ...       ...      ...   ...           ...  
4869      0.00      0.00     0.00  0.00             0  
4870      0.00      0.00     0.00  0.00             0  
4871      0.00      0.00     0.00  0.00             0  
4872      0.00      0.00     0.00  6.53             0  
4873      0.00      0.00     0.00  0.00             0  

[4874 rows x 59 columns]

In [ ]:
X=data.iloc[:,3:-1].values
y=data.iloc[:,-1].values
X

array([[4.90000e+00, 2.20400e+01, 4.28000e+00, ..., 1.06890e+03,
        5.86350e+02, 7.96000e+00],
       [5.59000e+00, 4.05100e+01, 5.59000e+00, ..., 9.17488e+03,
        1.38283e+03, 5.01000e+00],
       [2.54000e+00, 2.22500e+01, 3.50000e+00, ..., 1.26944e+03,
        4.83190e+02, 9.15000e+00],
       ...,
       [5.19000e+00, 3.11300e+01, 1.29700e+01, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [2.97800e+01, 7.46100e+01, 1.37700e+01, ..., 0.00000e+00,
        0.00000e+00, 6.53000e+00],
       [0.00000e+00, 2.95300e+01, 1.05500e+01, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00]])

In [ ]:
y

array([1, 1, 1, ..., 0, 0, 0])

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=0.2)

In [ ]:
from sklearn.tree import DecisionTreeRegressor
dreg=DecisionTreeRegressor()

In [ ]:
dreg.fit(xtrain,ytrain)
pred=dreg.predict(xtest)

In [ ]:
from sklearn.metrics import mean_squared_error,r2_score
score=r2_score(ytest,pred)
rmse=np.sqrt(mean_squared_error(ytest,pred))
score

-0.011921064391045677

In [ ]:
rmse

0.38430756913220915

4.random forest

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data=pd.read_csv('/content/cost-of-living.csv')
data=data.fillna(value=0)
data

Unnamed: 0                city      country     x1     x2     x3     x4  \
0              0               Delhi        India   4.90  22.04   4.28   1.84   
1              1            Shanghai        China   5.59  40.51   5.59   1.12   
2              2             Jakarta    Indonesia   2.54  22.25   3.50   2.02   
3              3              Manila  Philippines   3.54  27.40   3.54   1.24   
4              4               Seoul  South Korea   7.16  52.77   6.03   3.02   
...          ...                 ...          ...    ...    ...    ...    ...   
4869        4869        Peterborough    Australia   0.00   0.00   0.00   0.00   
4870        4870          Georgetown    Australia   0.00   0.00   0.00   0.00   
4871        4871  Ixtapa Zihuatanejo       Mexico   5.19  31.13  12.97   0.99   
4872        4872             Iqaluit       Canada  29.78  74.61  13.77   6.70   
4873        4873              Neiafu        Tonga   0.00  29.53  10.55  10.55   

        x5    x6    x7  ...     x47      x48     x49      x50      x51  \
0     3.67  1.78  0.48  ...   36.26   223.87  133.38   596.16   325.82   
1     4.19  3.96  0.52  ...  121.19  1080.07  564.30  2972.57  1532.23   
2     3.18  2.19  0.59  ...   80.32   482.85  270.15  1117.69   584.37   
3     1.90  2.91  0.93  ...   61.82   559.52  281.78  1754.40   684.81   
4     4.52  3.86  1.46  ...  108.30   809.83  583.60  2621.05  1683.74   
...    ...   ...   ...  ...     ...      ...     ...      ...      ...   
4869  0.00  0.00  0.00  ...    0.00     0.00    0.00     0.00     0.00   
4870  0.00  0.00  0.00  ...    0.00     0.00    0.00     0.00     0.00   
4871  0.00  1.82  0.62  ...  103.78   415.11  259.44   518.89   415.11   
4872  8.93  3.72  3.54  ...    0.00     0.00    0.00  2978.11  2978.11   
4873  0.00  0.00  2.11  ...    0.00     0.00    0.00     0.00     0.00   

           x52       x53      x54   x55  data_quality  
0      2619.46   1068.90   586.35  7.96             1  
1     17333.09   9174.88  1382.83  5.01             1  
2      2694.05   1269.44   483.19  9.15             1  
3      3536.04   2596.44   419.02  7.80             1  
4     21847.94  10832.90  2672.23  3.47             1  
...        ...       ...      ...   ...           ...  
4869      0.00      0.00     0.00  0.00             0  
4870      0.00      0.00     0.00  0.00             0  
4871      0.00      0.00     0.00  0.00             0  
4872      0.00      0.00     0.00  6.53             0  
4873      0.00      0.00     0.00  0.00             0  

[4874 rows x 59 columns]

In [ ]:
X=data.iloc[:,3:-1].values
y=data.iloc[:,-1].values

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=0.2)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rreg=RandomForestRegressor(n_estimators=10)

In [ ]:
rreg.fit(xtrain,ytrain)

RandomForestRegressor(n_estimators=10)

In [ ]:
pred=rreg.predict(xtest)
from sklearn.metrics import r2_score,mean_squared_error

In [ ]:
score=r2_score(ytest,pred)
rmse=np.sqrt(mean_squared_error(ytest,pred))
score

0.4810933279396604

In [ ]:
rmse

0.28924304392938904

5.support vector regression

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data=pd.read_csv('/content/cost-of-living.csv')
data=data.fillna(value=0)
data

Unnamed: 0                city      country     x1     x2     x3     x4  \
0              0               Delhi        India   4.90  22.04   4.28   1.84   
1              1            Shanghai        China   5.59  40.51   5.59   1.12   
2              2             Jakarta    Indonesia   2.54  22.25   3.50   2.02   
3              3              Manila  Philippines   3.54  27.40   3.54   1.24   
4              4               Seoul  South Korea   7.16  52.77   6.03   3.02   
...          ...                 ...          ...    ...    ...    ...    ...   
4869        4869        Peterborough    Australia   0.00   0.00   0.00   0.00   
4870        4870          Georgetown    Australia   0.00   0.00   0.00   0.00   
4871        4871  Ixtapa Zihuatanejo       Mexico   5.19  31.13  12.97   0.99   
4872        4872             Iqaluit       Canada  29.78  74.61  13.77   6.70   
4873        4873              Neiafu        Tonga   0.00  29.53  10.55  10.55   

        x5    x6    x7  ...     x47      x48     x49      x50      x51  \
0     3.67  1.78  0.48  ...   36.26   223.87  133.38   596.16   325.82   
1     4.19  3.96  0.52  ...  121.19  1080.07  564.30  2972.57  1532.23   
2     3.18  2.19  0.59  ...   80.32   482.85  270.15  1117.69   584.37   
3     1.90  2.91  0.93  ...   61.82   559.52  281.78  1754.40   684.81   
4     4.52  3.86  1.46  ...  108.30   809.83  583.60  2621.05  1683.74   
...    ...   ...   ...  ...     ...      ...     ...      ...      ...   
4869  0.00  0.00  0.00  ...    0.00     0.00    0.00     0.00     0.00   
4870  0.00  0.00  0.00  ...    0.00     0.00    0.00     0.00     0.00   
4871  0.00  1.82  0.62  ...  103.78   415.11  259.44   518.89   415.11   
4872  8.93  3.72  3.54  ...    0.00     0.00    0.00  2978.11  2978.11   
4873  0.00  0.00  2.11  ...    0.00     0.00    0.00     0.00     0.00   

           x52       x53      x54   x55  data_quality  
0      2619.46   1068.90   586.35  7.96             1  
1     17333.09   9174.88  1382.83  5.01             1  
2      2694.05   1269.44   483.19  9.15             1  
3      3536.04   2596.44   419.02  7.80             1  
4     21847.94  10832.90  2672.23  3.47             1  
...        ...       ...      ...   ...           ...  
4869      0.00      0.00     0.00  0.00             0  
4870      0.00      0.00     0.00  0.00             0  
4871      0.00      0.00     0.00  0.00             0  
4872      0.00      0.00     0.00  6.53             0  
4873      0.00      0.00     0.00  0.00             0  

[4874 rows x 59 columns]

In [ ]:
X=data.iloc[:,3:-1].values
y=data.iloc[:,-1].values

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
x_sc=StandardScaler()
y_sc=StandardScaler()
y=y.reshape(len(y),1)

In [ ]:
X=x_sc.fit_transform(X)
y=y_sc.fit_transform(y)

In [ ]:
from sklearn.svm import SVR

In [ ]:
sreg=SVR(kernel='rbf')

In [ ]:
sreg.fit(X,y)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [ ]:
pred=sreg.predict(X)
from sklearn.metrics import r2_score,mean_squared_error

In [ ]:
score=r2_score(y,pred)
rmse=np.sqrt(mean_squared_error(y,pred))
score

0.4369980466621587

In [ ]:
rmse

0.7503345609378801

# Comparing regression errors
1.MULTIPLE REGRESSION-0.344

2.POLYNOMIAL REGRESSION-0.0001

3.DECISION TREE-0.416

4.RANDOM FOREST-0.289

5.SUPPORT VECTOR-0.750


#Therefore,polynomial regression having least error is considered best

#CLASSIFICATION

1.logistic regression

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data=pd.read_csv('/content/cost-of-living.csv')
data=data.fillna(value=0)

In [ ]:
X=data.iloc[:,3:-1].values
y=data.iloc[:,-1].values

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=0.2)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtrain=sc.fit_transform(xtrain)
xtest=sc.transform(xtest)

In [ ]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(xtrain,ytrain)

LogisticRegression()

In [ ]:
pred=lr.predict(xtest)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
ac=accuracy_score(ytest,pred)
ac

0.8317948717948718

In [ ]:
cm=confusion_matrix(ytest,pred)
cm

array([[749,  46],
       [118,  62]])

2.support vector kernel

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data=pd.read_csv('/content/cost-of-living.csv')
data=data.fillna(value=0)

In [ ]:
X=data.iloc[:,3:-1].values
y=data.iloc[:,-1].values
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=0.2)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtrain=sc.fit_transform(xtrain)
xtest=sc.transform(xtest)

In [ ]:
from sklearn.svm import SVC
classifier=SVC(kernel='rbf')
classifier.fit(xtrain,ytrain)
pred=classifier.predict(xtest)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
ac=accuracy_score(ytest,pred)
ac

0.8676923076923077

In [ ]:
cm=confusion_matrix(ytest,pred)
cm

array([[772,  21],
       [108,  74]])

3.k nearest neighbours

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data=pd.read_csv('/content/cost-of-living.csv')
data=data.fillna(value=0)

In [ ]:
X=data.iloc[:,3:-1].values
y=data.iloc[:,-1].values
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=0.2)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtrain=sc.fit_transform(xtrain)
xtest=sc.transform(xtest)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knr=KNeighborsClassifier(n_neighbors=3)
knr.fit(xtrain,ytrain)
pred=knr.predict(xtest)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
ac=accuracy_score(ytest,pred)
ac

0.7856410256410257

In [ ]:
cm=confusion_matrix(ytest,pred)
cm

array([[629, 164],
       [ 45, 137]])

4.desision trees

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data=pd.read_csv('/content/cost-of-living.csv')
data=data.fillna(value=0)

In [ ]:
X=data.iloc[:,3:-1].values
y=data.iloc[:,-1].values
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=0.2)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtrain=sc.fit_transform(xtrain)
xtest=sc.transform(xtest)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(xtrain,ytrain)
pred=dtc.predict(xtest)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
ac=accuracy_score(ytest,pred)
ac

0.8512820512820513

In [ ]:
cm=confusion_matrix(ytest,pred)
cm

array([[727,  78],
       [ 67, 103]])

5. random forest

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data=pd.read_csv('/content/cost-of-living.csv')
data=data.fillna(value=0)

In [ ]:
X=data.iloc[:,3:-1].values
y=data.iloc[:,-1].values
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=0.2)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtrain=sc.fit_transform(xtrain)
xtest=sc.transform(xtest)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rc=RandomForestClassifier()
rc.fit(xtrain,ytrain)

RandomForestClassifier()

In [ ]:
pred=rc.predict(xtest)
from sklearn.metrics import accuracy_score,confusion_matrix
ac=accuracy_score(ytest,pred)
ac

0.8912820512820513

In [ ]:
cm=confusion_matrix(ytest,pred)
cm

array([[749,  35],
       [ 71, 120]])

# Comparing classifiers Accuracy
1.logistic regression-81%

2.support vector-88%

3.K nieghbour classifier-78%

4.decision tree-84%

5.random forest-89%

#Therefore,random forest having highest accuracy is considered the best.